services:
  - type: worker  
    name: tg-bot-recommender
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bot-database
          property: connectionString
      - key: TG_BOT_TOKEN
        sync: false